### ISSUE TITLE
Target .NET Standard in library projects

### ISSUE THREAD

**Issue by hankbeasley** [snatch-dev/Convey#10]
Shouldn't library projects target .NET Standard for more flexibility in different host projects?

**Comment by spetz** [comment]
AFAIR, we had some issues with updating all of the packages to `netstandard2.1`, thus we stick with `netcoreapp3.0`, as it has the direct reference to `ASP.NET Core` being part of system packages now.
We'll take a look once again whether it's possible to use .NET Standard (as we did in the past with previous versions of Convey based on `netstandard2.0`), but I can't make any promises at that point if it's going to work out.
