### ISSUE TITLE
Log payload deserialization exceptions

### ISSUE THREAD

**Issue by jmolla31** [snatch-dev/Convey#100]
https://github.com/snatch-dev/Convey/blob/eed6999d518c2bdc7014380d232ef75a000bc4c0/src/Convey.WebApi/src/Convey.WebApi/Extensions.cs#L339-L345

Exceptions thrown during payload deserializations are not logged, this makes debugging these errors difficult.

**Comment by jmolla31** [comment]
If this is considered a valid issue, I'm more than happy to work on it and submit a PR to be reviewed 😊

**Comment by spetz** [comment]
Good point, feel free to submit a PR! :)
