### ISSUE TITLE
Can WebApi handlers access the context?

### ISSUE THREAD

**Issue by VictorioBerra** [snatch-dev/Convey#14]
https://convey-stack.github.io/documentation/Web-API/

Docs show an endpoint like this:

```csharp
.Post<AddParcel>("parcels", (req, ctx) => ctx.Response.Created($"parcels/{req.ParcelId}"))))
```

And then they show a handler but it doesnt appear that you can get to `HttpContext` in a handler.

**Comment by spetz** [comment]
Do you mean that you can't access `HttpContext` in the lambda expression or something else is wrong?

**Comment by GooRiOn** [comment]
@VictorioBerra there's a an accessor for that purpose inside .NET Core called `IHttpContextAccessor`. This will allow you to access the context (it's build on top of `AsyncLocal<T>`) so it's different according to the async method context. However I'd recommend wrapping this in some sort of abstraction to avoid leaking the HTTP-related stuff into the handlers.

**Comment by VictorioBerra** [comment]
@GooRiOn ahhh I can just inject `IHttpContextAccessor` (or rather an abstraction). That makes much more sense.

I am unfamiliar with `AsyncLocal<T>`  but I get the general concept of accessing `IHttpContextAccessor` in a service during a request.

@spetz thanks for the quick reply, @GooRiOn answered the question for me, I was more or less thinking that there would be an overload of `HandleAsync` that exposed the context. IE:

```csharp
public class DeleteParcel : IRequest
{
    public Guid ParcelId { get; }

    public DeleteParcel(Guid parcelId)
    {
        ParcelId = parcelId;
    }
}

public class DeleteParcelHandler : IRequestHandler<DeleteParcel, int>
{
    public async Task HandleAsync(DeleteParcel request, HttpContext context)
    {
        // Deleted a parcel, let's return its ID.
        return ctx.Response.Created($"parcels/{request.ParcelId}");
    }
}
```
