### ISSUE TITLE
EventStorming

### ISSUE THREAD

**Issue by squizee** [snatch-dev/Convey#17]
Dorobicie Event Storming na Eventstore? :)

eventstore.org - wygląda to dobrze ;)

**Comment by spetz** [comment]
Hej,
Miałeś chyba na myśli Event Sourcing? Od tego są dedykowane biblioteki jak właśnie [Event Store](https://eventstore.org) czy [Marten](https://jasperfx.github.io/marten), więc póki co nie mamy na to planów.

**Comment by squizee** [comment]
Haha, tak tak, Sourcing :) Spoko :)
