### ISSUE TITLE
Do you have a preferred approach for versioning.

### ISSUE THREAD

**Issue by paulvanbladel** [snatch-dev/Convey#18]
Software evolves, there is progressive insight and as a result commands, queries, domain events and integration events need updating which usually means versioning.
This is an often underestimated pain point.
(See e.g. https://leanpub.com/esversioning)

Ideas?
Btw, very interesting project !

**Comment by spetz** [comment]
Hey,
Versioning is quite often a tricky part. There are a few things that can be done:
- Use some sort of contract testing e.g. [pact.io](https://docs.pact.io) (you can also use our port [pactify](https://github.com/snatch-dev/Pactify)) to ensure that data providers do not break the contracts.
- Ensure that when other services still use the previous versions of the contracts, you only add new properties to the types without removing the old ones (and once all of the consumers switch to the newer versions - remove the old properties).
- Run multiple versions of the same service in parallel e.g. API v1, API v2, etc. as long as the consumers still didn't upgrade themselves to the latest version (mostly useful when exposing the public APIs).
