### ISSUE TITLE
'IApplicationBuilder' does not contain a definition for 'UseConsul'.

### ISSUE THREAD

**Issue by BillCharlaftis** [snatch-dev/Convey#19]
Hi guys thanks for these really helpfull packages.
Reading your documentation I am trying to implement its contents. I am in 
https://convey-stack.github.io/documentation/HTTP/ 
and I have an issue trying to impement the part of useing consul. It is like that there is not any deffinition of UseConsul.

**Comment by spetz** [comment]
Hi,
We will update the docs, there's only `AddConsul()` which handles the service registration as a background task (`IHostedService`) and `UseConsul()` was removed.
