### ISSUE TITLE
AllowSynchronousIO issue with solution

### ISSUE THREAD

**Issue by NTTLuke** [snatch-dev/Convey#21]
Hi guys 
I found an issue using vs2019

I saw that AllowSynchronousIO is set only for Kestrel and since VS2019 uses also IISExpress maybe adding the same for IISServerOptions could be helpful. 

I wanted to send you a MR but strange errors happened with my git 🔢 

Awesome work guys !! 💪 
Congrats

**Comment by spetz** [comment]
Hey,
Thanks, fixed!
