### ISSUE TITLE
swagger giving me errors

### ISSUE THREAD

**Issue by murunwas** [snatch-dev/Convey#3]
When I tried to register swagger is giving me errors

`Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator': Failed to compare two elements in the array.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.SwaggerGen.ISchemaRegistryFactory Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistryFactory': Failed to compare two elements in the array.)'
`

![image](https://user-images.githubusercontent.com/8838943/67663762-e417e200-f96e-11e9-8545-237080b69d75.png)

**Comment by spetz** [comment]
We're aware of that issue, it works with `netstandard2.0` version (previous Convey packages), and we're going to migrate Swagger to the new version in order to fix it.

**Comment by GooRiOn** [comment]
Fixed that bug both for ASP.NET Core Controllers and Web API as well. Closing this issue. In case of having any trouble please reopen :)
