### ISSUE TITLE
Convey.WebApi / invocation of IRequestHandler

### ISSUE THREAD

**Issue by b-y-t-e** [snatch-dev/Convey#35]
Hello,
I have a problem with an invocation of simple IRequestHandler. The handler will never get invoked. 

> 
    public class Program
    {
        public static async Task Main(string[] args)
        {
            await WebHost
                .CreateDefaultBuilder(args)
                .ConfigureServices(services => services
                    .AddConvey()
                    .AddWebApi()
                    .Build())
                .Configure(app => app
                    .UseEndpoints(endpoints => endpoints
                        .Get("", ctx => ctx.Response.WriteJsonAsync(ctx.RequestServices.GetService<AppOptions>() ) )
                        .Delete<DeleteParcel>("parcels/{parcelId}")))
                .UseLogging()
                .Build()
                .RunAsync();
        }
    }
    public class DeleteParcel : IRequest
    {
        public int ParcelId { get; }
        public DeleteParcel(int parcelId)
        {
            ParcelId = parcelId;
        }
    }
    public class DeleteParcelHandler : IRequestHandler<DeleteParcel, int>
    {
        public async Task<int> HandleAsync(DeleteParcel request)
        {
            return request.ParcelId;
        }
    }

**Comment by PiotrFerenc** [comment]
change IRequest to ICommand and IRequestHandler to ICommandHandler

**Comment by b-y-t-e** [comment]
Thanks for response, but Command does not have any result type, which is crucial for me.

**Comment by PiotrFerenc** [comment]
plz see below:
https://github.com/devmentors/Pacco.Services.Customers/blob/master/src/Pacco.Services.Customers.Application/Commands/Handlers/ChangeCustomerStateHandler.cs#L31

https://github.com/devmentors/Pacco.Services.Customers/tree/master/src/Pacco.Services.Customers.Application/Exceptions

**Comment by PiotrFerenc** [comment]
```
    class CreateOrderHandler : ICommandHandler<CreateOrderCommand>
    {
        public Task HandleAsync(CreateOrderCommand command)
        {
          return Task.FromResult(command.Id);
        }
    }
```

**Comment by b-y-t-e** [comment]
Thanks for the answer! I know about ICommandHandler and ICommand interfaces (and I use them with no problem). However I would like to bend CQRS assumptions a little, and I would like that commands are able to return the value to the client. According to the documentation (https://convey-stack.github.io/documentation/Web-API/) IRequestHandler interface is ideal for this scenario, but the example from documentation does not work.

**Comment by Allann** [comment]
I understand the frustration, I recently swapped in MediatR (https://www.nuget.org/packages/MediatR/) with success, maybe if you are blocked this could be a solution?.

**Comment by GooRiOn** [comment]
Neither of the CQRS packages provide you such thing, however there's the `IRequestHandler<,>` type beeing provided by WebAPI package along with its internal registration:

https://github.com/snatch-dev/Convey/blob/5b9a36606bad36d071461d984413f3c4e5adeca6/src/Convey.WebApi/src/Convey.WebApi/Requests/IRequestHandler.cs

https://github.com/snatch-dev/Convey/blob/3c6fe48f17a115579c87767de8894390fea9d1d2/src/Convey.WebApi/src/Convey.WebApi/Extensions.cs#L109
