### ISSUE TITLE
 A circular dependency was detected for the service of type

### ISSUE THREAD

**Issue by mehrdad-goudarzi** [snatch-dev/Convey#52]
After update package version to 0.4.342
There is an error in EventHandler.
 A circular dependency was detected for the service of type
 'Convey.CQRS.Events.IEventHandler<>'. System.Collections.Generic.IEnumerable<Convey.CQRS.Events.IEventHandler<>> -> Convey.CQRS.Events.IEventHandler<>(Convey.Logging.CQRS.Decorators.EventHandlerLoggingDecorator<>) -> Convey.CQRS.Events.IEventHandler<>

**Comment by iharpeshka** [comment]
In 0.4.330 everything works well. This error appeared after https://github.com/snatch-dev/Convey/commit/8c9ba524ad14ac8b8015f99082eaaeba15738dfa#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by iharpeshka** [comment]
@spetz @GooRiOn ?

**Comment by mehrdad-goudarzi** [comment]
It is working at 0.4.349 version.

**Comment by spetz** [comment]
It was fixed by introducing the marker attribute `[Decorator]` that should be added on top of the decorator type to avoid a circular dependency (for command, event and query handlers).
