### ISSUE TITLE
What's the easiest way to use this library with azure service bus instead of rabbitmq?

### ISSUE THREAD

**Issue by paulvanbladel** [snatch-dev/Convey#56]
Very nice library !

What's the easiest way to use this library with azure service bus instead of rabbitmq?

**Comment by GooRiOn** [comment]
Hi,
thx for kind words! Honestly the only thing you could do is to implement it by yourself based on the abstraction provided in the `Convey.MessageBroker` package. For now we don't plan to add it by ourselves.
