### ISSUE TITLE
InboxMessages are not saving in EF when recieveing events and outbox is enabled and decorator added

### ISSUE THREAD

**Issue by majumajid** [snatch-dev/Convey#71]
InboxMessages are not saving in EF when recieveing events and outbox is enabled and decorator added

**Comment by majumajid** [comment]
I tried to generate PR. but unable to do that.
Kindly add following line before await transaction.CommitAsync(); in function public async Task HandleAsync(string messageId, Func<Task> handler)  under internal sealed class EntityFrameworkMessageOutbox<TContext> class
await _dbContext.SaveChangesAsync();

**Comment by spetz** [comment]
Fixed :)
