### ISSUE TITLE
[Vault leases] app broken after max_ttl expires

### ISSUE THREAD

**Issue by leoshusar** [snatch-dev/Convey#75]
Vault package does not have implemented getting new lease credentials after max_ttl expires.
It renews that lease until the max_ttl and then app becomes broken.
You currently have to restart your app every [max_ttl] so it can get new credentials.

With this update also other packages must be updated to use transient or scoped lifetime instead of singleton (MongoDB uses singleton and I think RabbitMQ too, don't know about the others).

**Comment by spetz** [comment]
Thanks, fixed according to your suggestion!
