### ISSUE TITLE
[Vault leases] Wrong expiration time after renewing

### ISSUE THREAD

**Issue by leoshusar** [snatch-dev/Convey#78]
Leases have wrong expiration time after renewing.
The problem is here:

```cs
public void Refresh(int duration)
{
    ExpiryAt = ExpiryAt.AddSeconds(duration);
}

...

lease.Refresh(renewedLease.LeaseDurationSeconds);
```

When you have lease with ttl 3600 seconds, it cannot go over that.
So when you have for example 10 seconds left and you renew it for another 3600 seconds, the lease expires in the maximum 3600 seconds but in `LeaseData` is 3610 seconds.

This causes those leases to expire, because it sends the renew command too late.

Here is my idea to fix this.

First let's change `Refresh` to accept double value.

```cs
public void Refresh(double duration)
{
    ExpiryAt = ExpiryAt.AddSeconds(duration);
}
```

Then change the renewing loop like this:

```cs
var beforeRenew = DateTime.UtcNow;
var renewedLease = await _client.V1.System.RenewLeaseAsync(lease.Id, lease.Duration);
lease.Refresh(renewedLease.LeaseDurationSeconds - (lease.ExpiryAt - beforeRenew).TotalSeconds);
```

and finally to stabilize the interval, change the delay to:

```cs
await Task.Delay(interval.Subtract(DateTime.UtcNow - now), stoppingToken);
```

I have created some 30 second long leases and ran this for a couple of hours and the difference between Vault's `ExpiryAt` and `LeaseData.ExpiryAt` was stable 140 ms - `LeaseData.ExpiryAt` was 140 ms later.

Any thoughts?

**Comment by spetz** [comment]
Thanks, fixed! :)
