### ISSUE TITLE
RabbitMq JaegerPlugin Message Invalid cast exception

### ISSUE THREAD

**Issue by mariuszkochanowski** [snatch-dev/Convey#79]
Włączone usługi:
RabbitMq, Jaeger

Po włączeniu pluginu JaegerPlugin dla rabbita
występuje błąd rzutowania podczas naprzemiennego wysyłania 2 różnych typów zdarzeń na kolejkę.
Dochodzi do próby rzutowania jednego typu zdarzenia na drugi
![image](https://user-images.githubusercontent.com/3482384/127147735-17f6510a-0d39-45b8-8842-f95f839cd271.png)

**Comment by spetz** [comment]
W jakim konkretnie przypadku jeśli chodzi o ustawienie exchange, queue i wiadomości?
