### ISSUE TITLE
Get authenticated user

### ISSUE THREAD

**Issue by scionwest** [snatch-dev/Convey#9]
I see from your documentation that you support using the standard `UseAuthentication` middleware, along with provisioning your own Jwt tokens via `Convey.Auth`. I'm not seeing anything in the docs or samples that show how to pull the user identity out of the bearer token sent along with the request.

Your samples shows the `CustomerId` being sent in as part of the command. Ideally, I'll pull this information from a claim within the Jwt token. A user can put any customer id they'd want - I need to use a signed token in order to know which user I need to update data on for.

Can you help point me in the right direction on how I would handle this use-case?

**Comment by spetz** [comment]
Hey,
Are you looking for a way to get the `UserId` (which can be any string) from the existing token? If that's the case, the solution is quite simple - it's a `sub` claim, that you can get directly from JWT as its base64 encoded string (as you suggested) unless I'm not understanding you correctly.

**Comment by scionwest** [comment]
Sorry, to clarify - I don't see how to get the JWT token. Am I supposed to just inject an instance of `IHttpContextAccessor` and pull it from the headers myself? If so, that's not a big deal. You have other services, middleware and services for interacting with auth but I didn't see anything explicit to pull the principle identity out easily.

Also, I'm not able to see an example for returning `401 Unauthorized`. I've seen how to send back a `201 Created` and a `404 Not Found` but I can't see how I am supposed to send back the `401` or mark a resource as requiring authorization in order to be hit.

**Comment by spetz** [comment]
Thanks for the clarification. Well, to get a token, you could use `IHttpContextAccessor` and pull it from the header as a string (it can be wrapped into a simple extension method), actually, I didn't think back then it might be needed.

Everything works with a standard authentication & authorization middleware, meaning that you can simply put [Authorize] attribute on top of your controllers/actions or add a custom middleware that might check the role/claims and set 401 response directly.

Speaking of custom methods such as `Created()`, `NotFound()` etc. - `Unauthorized()`, `Forbidden()` and a few have others have been just added.

**Comment by scionwest** [comment]
@spetz What if I'm just using handlers directly without any MVC middleware? All that I'm able to return back is a `Task` on the Command handlers and the handler for Queries is constrained to the response body type of `T`. I'm not sure how to specifically return back an HTTP status code from within a handler when not using MVC controllers. For instance, [in this handler](https://github.com/FocusMark/Services/blob/feature/todo/project-api/src/Services/Todo/Todo.Api/Commands/CreateProject.cs#L55) I can't return 401 Unauthorized if I grab the token via `IHttpContextAccessor` and determine this user is not authorized to hit use this query handler.

**Comment by spetz** [comment]
Ok, understood.
You should return status codes from handlers - authentication and authorization should be a different middleware (being run before you actually hit your handlers etc.). In that case, you can do simple extension methods such as [this one](https://github.com/devmentors/Pacco.Services.Identity/blob/master/src/Pacco.Services.Identity.Infrastructure/Extensions.cs#L84). Within handlers, you can throw an exception, or build some additional decorators on top of them that will validate the incoming requests and plug it into the pipeline.

**Comment by spetz** [comment]
Ok, understood.
You shouldn't return status codes from handlers - authentication and authorization should be a different middleware (being run before you actually hit your handlers, etc.). In that case, you can do simple extension methods such as this one. Within handlers, you can throw an exception, or build some additional decorators on top of them that will validate the incoming requests and plug it into the pipeline.

**Comment by spetz** [comment]
Ok, understood.
You shouldn't return status codes from handlers - authentication and authorization should be a different middleware (being run before you actually hit your handlers, etc.). In that case, you can do simple extension methods such as [this one](https://github.com/FocusMark/Services/blob/feature/todo/project-api/src/Services/Todo/Todo.Api/Commands/CreateProject.cs#L55). Within handlers, you can throw an exception, or build some additional decorators on top of them that will validate the incoming requests and plug it into the pipeline.

**Comment by spetz** [comment]
Ok, understood.
You shouldn't return status codes from handlers - authentication and authorization should be a different middleware (being run before you actually hit your handlers, etc.). In that case, you can do simple extension methods such as [this one](https://github.com/devmentors/Pacco.Services.Identity/blob/master/src/Pacco.Services.Identity.Infrastructure/Extensions.cs#L84). Within handlers, you can throw an exception, or build some additional decorators on top of them that will validate the incoming requests and plug it into the pipeline.

**Comment by scionwest** [comment]
@spetz Awesome thanks for the guidance. I'll work towards handling things that way.
